org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true

android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# aarch64 关键适配：Google 只发布 x86_64 版 aapt2，AGP 默认会从 Maven 拉 x64 版本，
# 在 arm64 上会以 "Exec format error" 失败。这里改指向 arm64 原生 aapt2。
android.aapt2FromMavenOverride=/opt/sdk/aapt2-bin/aapt2
android.enableResourceOptimizations=false
